import React from "react";
import html2pdf from "html2pdf.js";
import { Button } from "@/components/ui/button";
import { Download } from "lucide-react";

interface ReportGeneratorProps {
  reportData: {
    clientName: string;
    month: number;
    year: number;
    printerSerial: string;
    bwOld: number;
    bwNew: number;
    colorOld: number;
    colorNew: number;
    bwPrinted: number;
    colorPrinted: number;
    bwIncluded: number;
    colorIncluded: number;
    bwExceeded: number;
    colorExceeded: number;
  };
}

export const ReportGenerator: React.FC<ReportGeneratorProps> = ({ reportData }) => {
  const handleDownloadPdf = () => {
    const element = document.getElementById("pdf-report-template");
    
    // Quick un-hide element purely for PDF render
    if (element) {
      element.style.display = "block";
      const opt = {
        margin: 1,
        filename: `Usage_Report_${reportData.clientName}_${reportData.month}_${reportData.year}.pdf`,
        image: { type: 'jpeg', quality: 0.98 },
        html2canvas: { scale: 2 },
        jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' }
      };

      html2pdf().from(element).set(opt).save().then(() => {
        element.style.display = "none";
      });
    }
  };

  return (
    <>
      <Button variant="default" onClick={handleDownloadPdf}>
        <Download className="w-4 h-4 mr-2" />
        Download PDF
      </Button>

      {/* Hidden print template layout */}
      <div id="pdf-report-template" style={{ display: "none", padding: "40px", fontFamily: "sans-serif", backgroundColor: "white", color: "black" }}>
        <h1 style={{ fontSize: "24px", fontWeight: "bold", borderBottom: "2px solid #ccc", paddingBottom: "10px" }}>
          Usage Report
        </h1>
        <div style={{ marginTop: "20px", display: "flex", justifyContent: "space-between" }}>
          <div>
            <strong>Client:</strong> {reportData.clientName} <br />
            <strong>Printer Serial:</strong> {reportData.printerSerial}
          </div>
          <div style={{ textAlign: "right" }}>
            <strong>Period:</strong> {reportData.month}/{reportData.year}
          </div>
        </div>

        <table style={{ width: "100%", marginTop: "30px", borderCollapse: "collapse" }}>
          <thead>
            <tr style={{ backgroundColor: "#f3f4f6", textAlign: "left" }}>
              <th style={{ padding: "12px", border: "1px solid #ddd" }}>Print Type</th>
              <th style={{ padding: "12px", border: "1px solid #ddd" }}>Old Counter</th>
              <th style={{ padding: "12px", border: "1px solid #ddd" }}>New Counter</th>
              <th style={{ padding: "12px", border: "1px solid #ddd" }}>Pages Printed</th>
              <th style={{ padding: "12px", border: "1px solid #ddd" }}>Included limit</th>
              <th style={{ padding: "12px", border: "1px solid #ddd" }}>Exceeded</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td style={{ padding: "12px", border: "1px solid #ddd", fontWeight: "bold" }}>Black & White</td>
              <td style={{ padding: "12px", border: "1px solid #ddd" }}>{reportData.bwOld}</td>
              <td style={{ padding: "12px", border: "1px solid #ddd" }}>{reportData.bwNew}</td>
              <td style={{ padding: "12px", border: "1px solid #ddd" }}>{reportData.bwPrinted}</td>
              <td style={{ padding: "12px", border: "1px solid #ddd" }}>{reportData.bwIncluded}</td>
              <td style={{ padding: "12px", border: "1px solid #ddd", color: reportData.bwExceeded > 0 ? "red" : "black" }}>
                {reportData.bwExceeded}
              </td>
            </tr>
            <tr>
              <td style={{ padding: "12px", border: "1px solid #ddd", fontWeight: "bold" }}>Color</td>
              <td style={{ padding: "12px", border: "1px solid #ddd" }}>{reportData.colorOld}</td>
              <td style={{ padding: "12px", border: "1px solid #ddd" }}>{reportData.colorNew}</td>
              <td style={{ padding: "12px", border: "1px solid #ddd" }}>{reportData.colorPrinted}</td>
              <td style={{ padding: "12px", border: "1px solid #ddd" }}>{reportData.colorIncluded}</td>
              <td style={{ padding: "12px", border: "1px solid #ddd", color: reportData.colorExceeded > 0 ? "red" : "black" }}>
                {reportData.colorExceeded}
              </td>
            </tr>
          </tbody>
        </table>

        <div style={{ marginTop: "40px", fontSize: "12px", color: "#666", textAlign: "center" }}>
          Document automatically generated by Contract Manager.
        </div>
      </div>
    </>
  );
};
